version: "3.5"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}:/var/www/html/
    environment:
      MYSQL_HOST: "${DB_HOST}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      INSTANCE_NAME: "${INSTANCE_NAME}"
      PROJECT_COLOR: "${PROJECT_COLOR}"
    container_name: ${DOCKER_IMAGE_PREFIX}php
    restart: always 
  apache:
    build:
      context: './apache/'
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "${EXTERNAL_APACHE_PORT}:80"
    volumes:
      - ${PROJECT_ROOT}:/var/www/html/
    container_name: ${DOCKER_IMAGE_PREFIX}apache
    restart: always 
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - "${EXTERNAL_MYSQL_PORT}:3306"
    volumes:
      - chefmaesters_data:/var/lib/mysql
    networks:
      - backend
    environment:
      TZ: "${TZ}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: ${DOCKER_IMAGE_PREFIX}mysql
  # mariadb:
  #   image: mariadb:${MARIADB_VERSION}
  #   restart: always
  #   ports:
  #     - "${EXTERNAL_MARIADB_PORT}:3306"
  #   volumes:
  #     - chefmaesters_data_mariadb:/var/lib/mysql
  #   networks:
  #     - backend
  #   environment:
  #     MYSQL_DATABASE: "${DB_NAME}"
  #     MYSQL_ROOT_USER: "${DB_USERNAME}"
  #     MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
  #   container_name: ${DOCKER_IMAGE_PREFIX}mariadb
    
networks:
  frontend:
    name: ${DOCKER_IMAGE_PREFIX}frontend
  backend:
    name: ${DOCKER_IMAGE_PREFIX}backend
volumes:
    chefmaesters_data:
    chefmaesters_data_mariadb: